### ISSUE TITLE
리뷰 등록 API 리팩토링 및 SpecData 조회 API 구현

### ISSUE THREAD

**Issue by choidongkuen** [BETTER-iTER/Server#101]
## 설명
> 리뷰 등록 API 리팩토링 및 SpecData 조회 API 구현
## To-do
- [x] 기존 리뷰 등록 API 리팩토링
- [x] SpecData 조회 API 구현
- [x] Category 조회 API 구현
- [x] 테스트 코드 작성 및 검증
