### ISSUE TITLE
리뷰 등록 API 및 관련 기능 테스트 코드 작성

### ISSUE THREAD

**Issue by choidongkuen** [BETTER-iTER/Server#105]
## 설명
> 기존 구현한 리뷰 등록 API 및 관련 기능 테스트 코드을 구현합니다.

## To-do
- [x] 리뷰 등록 API 테스트
- [x] `UserService` 서비스 레이어 테스트
- [x] 회원 정보 가져오기 API 테스트
- [x] 리뷰 spec data 조회 API 테스트
- [x] 홈화면 조회 API 테스트
- [x] Users 엔티티 리팩토링
