### ISSUE TITLE
리뷰 조회 API 관련 쿼리 최적화 및 리뷰 검색 API 구현

### ISSUE THREAD

**Issue by choidongkuen** [BETTER-iTER/Server#110]
## 설명
> 리뷰 조회시 나가는 sql 쿼리를 최적화 및 리뷰 검색 API 구현

## To-do
- [x] 리뷰 조회시 sql 쿼리 이해 후 최적화
- [x] 리뷰 검색 API 구현
- [x] 카테고리 이미지 url 추가
- [x] 테스트
