### ISSUE TITLE
기획 변경에 따른 기존 조회 관련 API 전반적인 수정 및 검색 결과 필터링 + 리뷰 상세 조회 API 구현

### ISSUE THREAD

**Issue by choidongkuen** [BETTER-iTER/Server#116]
## 설명
> 기획 변경에 따른 기존 조회 관련 API에 대한 전반적인 수정을 진행하며 검색 결과 필터링 진행합니다.

## To-do
- [x] 리뷰 조회 API 리팩토링
- [x] 검색 결과 필터링
- [x] 리뷰 상세 조회 
- [x] 테스트
