### ISSUE TITLE
Job Enum class 추가 및 리뷰 상세 조회 API 리팩토링

### ISSUE THREAD

**Issue by choidongkuen** [BETTER-iTER/Server#121]
## 설명
> 직업을 의미하는 Job Enum class 상수 추가 및 리뷰 상세 조회 API 을 리팩토링합니다.

## To-do
- [ ] Job Enum class 추가
- [ ] 리뷰 상세 조회 API 리팩토링
- [ ] 테스트 코드 작성 및 테스트
