### ISSUE TITLE
전문가 유저가 쓴 리뷰 리스트 조회 및 카테고리 필터 추가 + API 구현 및 카테고리 이미지 추가 및 홈 도메인 코드 리팩토링

### ISSUE THREAD

**Issue by choidongkuen** [BETTER-iTER/Server#131]
## 설명
> 필요한 필터 기능을 추가하고 카테고리 이미지 추가 + 코드 리팩토링을 진행합니다.

## To-do
- [x] 전문가 유저가 쓴 리뷰 리스트 조회 API 
- [x] 홈 도메인 코드 리팩토링 및 테스트 진행
- [x] 카테고리 기타 이미지 추가
- [x] 테스트 코드 작성 및 테스트 진행
