### ISSUE TITLE
리뷰 상세 조회 반환 필드 추가 및 Comment 엔티티 필드 수정

### ISSUE THREAD

**Issue by choidongkuen** [BETTER-iTER/Server#139]
## 설명
> 리뷰 상세 조회 API 의 반환 필드를 추가 합니다.

## To-do
- [x] 리뷰 상세 조회 API 의 반환 필드 추가
- [x] Comment 필드 수정
- [x] 테스트 코드 작성 및 테스트
