### ISSUE TITLE
리뷰 비교 제품 필드 추가 및 관련 로직 추가

### ISSUE THREAD

**Issue by choidongkuen** [BETTER-iTER/Server#141]
## 설명
> 리뷰 엔티티에 비교 제품 필드 추가 및 관련 로직을 추가합니다.

## To-do
- [x] 리뷰 엔티티 비교 제품 필드 추가
- [x] 추가된 비교 제품 필드에 따른 로직 추가 및 변경
- [x] 테스트 코드 수정 및 테스트
- [x] 리뷰 상세 작성자 이름 닉네임 반환하도록 수정
