### ISSUE TITLE
리뷰 좋아요 취소 API 구현 및 마이페이지,댓글 관련 코드 리팩토링

### ISSUE THREAD

**Issue by choidongkuen** [BETTER-iTER/Server#143]
## 설명
> 리뷰 좋아요 취소 API 을 구현하며 기존 마이페이지,댓글 관련 코드를 리팩토링합니다.

## To-do
- [x] 리뷰 좋아요 취소 API 구현
- [x] 마이페이지, 댓글 관련 코드 리팩토링
- [x] 테스트 코드 작성 및 테스트
