### ISSUE TITLE
FCM 기반 알림 환경 구현

### ISSUE THREAD

**Issue by luke0408** [BETTER-iTER/Server#156]
## 설명
> FCM을 활용한 알림 기능 구현

## To-do
- [ ] FCM 환경 세팅
- [ ] Firebase 환경 세팅
- [ ] 알림 기능 구현
  - [ ] 알림 test(개인)
  - [ ] 알림 test(단체)

**Comment by luke0408** [comment]
### firebase 환경 세팅 관련 자료
- https://kbwplace.tistory.com/179
- https://data-make.tistory.com/768
- https://seungwoolog.tistory.com/88
- https://donghun.dev/Firebase-Cloud-Messaging
- https://github.com/Team-Shaka/Briefing-Backend/blob/develop/Briefing-Api/src/main/java/com/example/briefingapi/config/firebaseConfig.java
