### ISSUE TITLE
Test 환경 구축

### ISSUE THREAD

**Issue by luke0408** [BETTER-iTER/Server#17]
## 설명
> test를 위한 환경 및 가이드 라인 구축

참고자료

[ Base ]
- [SwaggerUI + Spring REST Docs 함께 사용하기(feat. Rest Assured)](https://jwkim96.tistory.com/274)
- [Spring Guide](https://cheese10yun.github.io/spring-guide-test-1/)
- [JPA 기반 테스트 코드 작성 팁](https://cheese10yun.github.io/jpa-test-support/)

[ 단순 JUnit 관련 ]
- [Junit5 with Spring boot](https://cheese10yun.github.io/junit5-in-spring/)

[ MockMVC + JUnit 관련 ]
- [Spring REST Docs 적용 및 최적화 하기](https://backtony.github.io/spring/2021-10-15-spring-test-3/)
- [Spring Boot - JUnit5 +MockMvc + Mockito로 Unit test 작성하기](https://velog.io/@tanggu01/GDSC-Spring-Boot-JUnit5-MockMvc-Mockito%EB%A1%9C-Unit-test-%EC%9E%91%EC%84%B1%ED%95%98%EA%B8%B0)
- [Spring REST Docs](https://cheese10yun.github.io/spring-rest-docs/)

[ Rest-Assured + JUnit 관련 ]
- [JUnit 5 and Rest Assured using Extension API](https://blog.aspiresys.pl/technology/junit-5-rest-assured-using-extension-api/)

## To-do
- [x] MockMVC + mockito + Junit5
- [x] 통합 테스트 환경 구축
- [x] 유닛 테스트 환경 구축

**Comment by luke0408** [comment]
## 체크리스트

> 아래의 질문에 대한 답변 작성

## 왜? test code를 작성해야 하는가

(작성 중)

## 현재 어떤 목적 달성하기 위해 test code를 써야하는가?

(작성 중)

## test code 작성시 발생하는 비용에는 어떤 것이 있는가?

(작성 중)

## 위 질문의 내용을 정리하라

(작성 중)

## 요약을 다시 보면서 필요한 것과 필요하지 않는 것을 배제하라

(작성 중)
