### ISSUE TITLE
일반 회원 가입 등을 포함한 회원 인증 기능 구현 및 회원 일반 기능 구현

### ISSUE THREAD

**Issue by choidongkuen** [BETTER-iTER/Server#19]
## 설명
> 일반 회원 가입 등을 포함한 회원 인증 기능 구현 및 회원 일반 기능 구현

## To-do
- [x] 기존 JwtAuthenticationFilter 및 JwtAuthenticationEntryPoint 보완 및 수정
- [x] 기존  User Entity 리팩토링
- [x] `일반 회원가입 API & 일반 로그인 API & 로그아웃 API` 등 관련 API 구현 
- [x] 메일을 통한 인증번호 발급 로직 구현
- [x] Spring Security 설정 구현
