### ISSUE TITLE
회원 및 인증 기능 전체 보완 및 리팩토링

### ISSUE THREAD

**Issue by choidongkuen** [BETTER-iTER/Server#23]
## 설명
> 현재까지 구현된 회원 및 인증 기능 보완 및 리팩토링 작업을 합니다.

## To-do
- [x] 전체 코드 리팩토링
- [x] 구현된 회원 과 인증 API 전체 테스트 및 피드백 반영
- [x] AccessDeniedHandler 구현
- [x] 카카오 회원가입 API
- [x] 닉네임 중복 여부 확인 API
