### ISSUE TITLE
CI 수정 및 CD 구축

### ISSUE THREAD

**Issue by choidongkuen** [BETTER-iTER/Server#25]
## 설명
> 기존 CI.yml 수정 및 CD 구축을 완성합니다.

## To-do
- [x] CI.yml 수정
- [x] CD(Continuous Deploy) 구현 및 통합
- [ ] Ec2 Server 에 env 파일 생성
