### ISSUE TITLE
일반 로그인 구현 및 기존 CD(contiuous deploy) 테스트

### ISSUE THREAD

**Issue by choidongkuen** [BETTER-iTER/Server#27]
## 설명
> 일반 로그인(Email,Password) 을 구현 마무리 및 EC2 ubuntu server 에서 CD 테스트를 진행합니다.

## To-do
- [ ] UsernamePasswordFilter 관련 필터 구현
- [ ] 인증 로직 구현 및 테스트
- [ ] CD 테스트 및 EC2 server docker container 구동
