### ISSUE TITLE
REVIEW entity 구현

### ISSUE THREAD

**Issue by luke0408** [BETTER-iTER/Server#33]
## 설명
> REVIEW 관련 entity 구현 (FO)

## To-do
- [x] REVIEW entity
- [x] REVIEW_LIKE entity
- [x] REVIEW_SCRAP entity
- [x] REVIEW_IMG entity
- [x] REVIEW_SPEC entity
