### ISSUE TITLE
익셉션 Enum 클래스 및 익셉션 핸들러 구현

### ISSUE THREAD

**Issue by choidongkuen** [BETTER-iTER/Server#49]
## 설명
> Exception 관련 작업을 진행합니다.

## To-do
- [x] 유저 인증 및 일반 기능 관련된 관련된 예외 enum 상수 추가
- [x] ExceptionHandler(UserHandler) 구현
- [x] 회원 인증/인가 및 일반 기능 전체 테스트
- [x] ElastiCache 구축
