### ISSUE TITLE
홈 화면 API 구현

### ISSUE THREAD

**Issue by choidongkuen** [BETTER-iTER/Server#69]
## 설명
> 홈 화면 API 구현합니다.

## To-do
- [x] HomeController, HomeService 구현
- [x] Home 에서 필요한 로직 추가 구현
- [x] Entity 추가 리팩토링
- [x] Category, UserCategory 관련 작업
