### ISSUE TITLE
Exception 핸들러 구현

### ISSUE THREAD

**Issue by luke0408** [BETTER-iTER/Server#7]
## 설명
> 에러 반환 값에 대한 익셉션 핸들러 정의

## To-do
- [x] 글로벌 예외 핸들러 생성하기
  - [x] 4xx 에러
  - [x] 5xx 에러
  - [x] 커스텀 exception 클래스 정의하기
  - [x] 커스텀 에러 코드 값 정의하기
- [x] 공통 응답 폼 정의
  - [x] 성공 응답 정의
  - [x] 예외 응답 정의
  - [x] 데이터 유효성 응답 정의

**Comment by luke0408** [comment]
[20230924]  @luke0408

## ✅ Done
- 코드 정의 및 구현 완료
  - GlobalExceptionHandler 구현
  - GeneralException 구현
  - ErrorCode 구현
  - BaseResponse -> ResponseDto 변경

## ✍️ In-Progress 
- [ ] GlobalException 작동 여부 체크
- [ ] 공동 응답 폼 적용 여부 체크
- [ ] 커스텀 Exception 관련
  - [ ] 핸들러 사용 방법 문서화
  - [ ] 커스텀 Exception 동작 여부 확인
