### ISSUE TITLE
최근 검색어 조회,추가 API 구현

### ISSUE THREAD

**Issue by choidongkuen** [BETTER-iTER/Server#79]
## 설명
> 검색 시 최근 검색어 조회,추가 API 을 구현합니다.

## To-do
- [x] Redis 괸련 코드 구현
- [x] 최근 검색어 조회 API 구현
- [x] 최근 검색어 추가 API 구현
- [x] 테스트
