### ISSUE TITLE
Comment Swagger 명세 추가

### ISSUE THREAD

**Issue by luke0408** [BETTER-iTER/Server#92]
## 설명
> Swagger 명세 추가

## To-do
- [x] comment 생성 명세
- [x] comment 삭제 명세
- [x] comment 조회 명세
