### ISSUE TITLE
마이페이지 profile api 제작

### ISSUE THREAD

**Issue by luke0408** [BETTER-iTER/Server#98]
## 설명
> 마이페이지 profile 관련 api 제작

## To-do
- [ ] api 제작
  - [ ] user profile 조회
  - [ ] user profile 수정
  - [ ] 관심 카테고리 수정
- [ ] api 테스트
  - [ ] user profile 조회
  - [ ] user profile 수정
  - [ ] 관심 카테고리 수정
